---
    ip: 192.168.0.10
    box: desafio-front-end
    name: desafio-front-end-dev
    hostname: vm.desafio-frontend.local
    provider: virtualbox
    ram: 256
    cpus: 1
    gui: false
    projects-folder: "/www"
